# Generated by Django 4.2.4 on 2023-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/unknown_user.jpg', upload_to='images/', verbose_name='images'),
        ),
    ]
